### PR TITLE
submission

### PR DESCRIPTION
**Pull request by merjemaa**

### CODE REVIEW

**Comment by amelavm** [comment]
Dear Merjema, from now on you need to add us as reviewers. You didn't add us as collaborators on time.

**Comment by merjemaa** [comment]
Dear professor,
I added you as collaborators as it was shown in assignment 1 description. I
had no idea that I also had to add you as reviewers. Also I tried to assign
issues to you and assistants but it didn't work. Here are the pictures I
took just in case.

Best regards,
Merjema Šahbegović

**Comment by amelavm** [comment]
@merjemaa kao što možeš vidjeti iznad, postoji conflict koji treba da se resolve-a, kako bismo uradili merge. Molim te samo da resolve-aš conflict.

**Comment by merjemaa** [comment]
Asistentica je slučajno preko mog accounta merge-ala pull request. Da Vam na vrijeme javim.

**Pull request merged**
